language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - 'node'
  - 'lts/*'
before_install:
  - npm install -g npm@5
  - npm install -g greenkeeper-lockfile@1
jobs:
  include:
    - stage: test
      script:
        - npm run build
        - npm run build:prod
        - npm run lint
        - npm run test
      before_script: greenkeeper-lockfile-update
      after_script: greenkeeper-lockfile-upload
    - stage: deploy
      if: branch = master
      script:
        - npm run deploy
